### ISSUE TITLE
Collaborate?

### ISSUE THREAD

**Issue by mrjackphil** [tadashi-aikawa/obsidian-quick-jump-plugin#2]
Hey, that's jump-to-link plugin creator. Can we discuss a collab on that functionality? 

There are different options I can suggest. Like merging my plugin into yours or another way around. 

I had not much time to fix the issue in jump-to-link plugin but might be you'll help me with it?

**Comment by tadashi-aikawa** [comment]
Hi, @mrjackphil. Thank your for the attractive offer!

First of all, Sorry, I decided not to collaborate with anyone because it is very costly for me.

I like your plugin very much, and I had attempted to support Live preview by creating PR. But it was not easy to apply CM6 implementations... Also, both CM5 and CM6. 

I read https://github.com/mrjackphil/obsidian-jump-to-link/issues/27 and understood that you want to support CM6, but you don't have much time.

So I created this plugin temporarily but will not publish it as a community plugin. The reason for this is that I feel it is best for us that jump-to-link be compatible with CM6 😄 

If you need snippets of my code, it would be great, and I want to help you as well as I can 👍 

Best regards.

**Comment by mrjackphil** [comment]
@tadashi-aikawa I've fixed CM6 support in **v0.3.0**. Now it should support CM5 and CM6 with both regexp and link functionality. Thank you so much for provided examples.

**Comment by tadashi-aikawa** [comment]
@mrjackphil 
Super quick! And it works perfectly more than my plugin! Thank you for your great work 😄
